export type MotoModel = {
  slug: string;
  name: string;
  image: string;
  summary: string;
  audience: string;
  specs: string[];
};

export const malcorModels: MotoModel[] = [
  {
    slug: "racer-r-160",
    name: "Malcor Racer R 160",
    image: "/malcor-racer-r-160cc.jpg",
    summary: "Pit motard 160cc con chasis de acero al cromo y configuracion enfocada a asfalto.",
    audience: "Para pilotos que quieren agilidad y respuesta en tandas sin ir a 190cc.",
    specs: [
      "Motor Z155 ultima version con filtro de aceite interno y plato magnetico ligero.",
      "Radiador de aceite XL y latiguillos metalicos.",
      "Horquilla 630mm replica Marzocchi con barras de 37mm, regulable en compresion y rebote.",
      "Amortiguador DNM MT-HRC 325mm con muelle 800lbs.",
      'Llantas aligeradas 2.5" delantera y 3" trasera.',
      "Discos floreados 220mm delantero y 190mm trasero.",
      "Chasis acero al cromo, subchasis rebajado y basculante 440mm.",
      "Extras: manillar bajo replica Renthal, cadena KMC 420 oro y silencioso con punta de carbono.",
    ],
  },
  {
    slug: "racer-r-190-special-edition",
    name: "Malcor Racer R 190 Special Edition",
    image: "/malcor-racer-r-190cc-special-edition.jpg",
    summary: "Edicion especial con motor ZS190 y extras orientados a competir.",
    audience: "Para pilotos que quieren una 190cc lista para circuito con equipamiento superior.",
    specs: [
      "Motor ZS190 ultima version con arranque a patada.",
      "Altura de asiento: 75cm.",
      "Horquilla 630mm replica Marzocchi regulable en compresion y rebote.",
      "Amortiguador trasero DNM HT-HRC 325mm totalmente regulable.",
      "Chasis acero al cromo con basculante recto de 440mm.",
      'Llantas de aleacion 2.5" delantera y 3" trasera.',
      "Discos 220mm delantero y 190mm trasero, discos flotantes.",
      "Freno delantero radial XFront.",
      "Radiador XL y latiguillos metalicos.",
      "Extras: asiento CRF70 bicolor, manetas CNC y cadena KMC 420.",
    ],
  },
  {
    slug: "super-racer-160",
    name: "Malcor Super Racer 160",
    image: "/malcor-super-racer-160cc.jpg",
    summary: "Version 160cc mejorada con radiador de gran caudal y componentes de serie avanzados.",
    audience: "Para pilotos que buscan una 160cc estable y completa para circuito.",
    specs: [
      "Motor ZS160 ultima version.",
      "Radiador de gran caudal y latiguillos metalicos.",
      "Horquillas 710mm replica Marzocchi (37mm) regulables en compresion y rebote.",
      "Amortiguador DNM MT-BAG 315mm 800lbs regulable en compresion, extension y rebote.",
      'Llantas ligeras 4 taladros 2.5" delantera y 3" trasera.',
      "Frenos con disco delantero 220mm y trasero 190mm.",
      "Chasis Malcor Best Frame estetica KTM y basculante recto 440mm.",
      "Dimensiones: 80cm asiento, 99cm manillar, 123.5cm entre ejes.",
    ],
  },
  {
    slug: "super-racer-r-190",
    name: "Malcor Super Racer R 190",
    image: "/malcor-super-racer-r-190cc.jpg",
    summary: "190cc con estetica racing y equipo completo de gama alta para asfalto.",
    audience: "Para pilotos altos o avanzados que quieren un rendimiento superior en pista.",
    specs: [
      "Motor ZS190 ultima version con filtro de aceite interno y plato magnetico ligero.",
      "Horquillas full adjust 710mm replica Marzocchi (37mm).",
      "Amortiguador trasero DNM MT-BAG 325mm 800lbs.",
      'Llantas aligeradas 2.5" delantera y 3" trasera con bujes huecos.',
      "Freno delantero radial Overmad 4 pistones.",
      "Discos flotantes 220mm delantero y 190mm trasero.",
      "Chasis grande con estetica KTM, apto para pilotos altos.",
      "Extras: asiento antideslizante, manillar bajo replica Renthal y silencioso con cola de carbono.",
    ],
  },
  {
    slug: "super-racer-smr-160",
    name: "Malcor Super Racer SMR 160",
    image: "/malcor-super-racer-smr-160cc.jpg",
    summary: "SMR 160 con chasis de aluminio reforzado y motor ZS155 ultima version.",
    audience: "Para pilotos que quieren una supermotard ligera y estable.",
    specs: [
      "Motor ZS155 ultima version con filtro de aceite interno y plato magnetico ligero.",
      "Chasis de aluminio propio con 6.5kg menos frente al acero.",
      "Basculante recto extralargo de 440mm.",
      "Horquillas 710mm full adjust replica Marzocchi (37mm).",
      "Amortiguador DNM MT-BAG 315mm 800lbs regulable.",
      'Llantas extraligeras 2.5" delantera y 2.75" trasera.',
      "Discos flotantes 220mm delantero y 190mm trasero.",
      "Dimensiones: 80cm asiento, 99cm manillar, 123.5cm entre ejes.",
    ],
  },
  {
    slug: "super-racer-smr-190",
    name: "Malcor Super Racer SMR 190",
    image: "/malcor-super-racer-smr-190cc.jpg",
    summary: "SMR 190 con chasis de aluminio y tijas CNC ajustables.",
    audience: "Para pilotos competitivos que buscan el maximo rendimiento en asfalto.",
    specs: [
      "Motor ZS190 ultima version con arandela del drum y plato magnetico ligero.",
      "Chasis de aluminio con reduccion de peso de 6.5kg.",
      "Tijas CNC ajustables.",
      "Horquillas full adjust 710mm replica Marzocchi (37mm).",
      "Amortiguador DNM MT-BAG 325mm 800lbs.",
      'Llantas extraligeras 2.5" delantera y 2.75" trasera (3 taladros).',
      "Freno delantero 4 pistones con freno radial XFront.",
      "Discos 220mm delantero y 190mm trasero.",
      "Radiador XL y latiguillos metalicos.",
    ],
  },
];

export const imrModels: MotoModel[] = [
  {
    slug: "copa-alevin-90",
    name: "IMR Copa Alevin 90",
    image: "https://impormotor.com/19443-home_default/imr-copa-alevin-90.jpg",
    summary: "Pitbike 90cc 4T ligera con horquilla invertida y llantas de 10 pulgadas.",
    audience: "Para iniciacion y pilotos jovenes en circuito de asfalto.",
    specs: [
      "Motor 4T 90cc monocilindrico refrigerado por aire.",
      "Potencia indicada: 5,9cv (4,33kw).",
      "Cambio semiautomatico; aceite motor 750ml.",
      "Chasis y basculante de acero.",
      "Horquilla invertida 650mm, barras 37mm, anclaje axial.",
      "Amortiguador DNM 260mm.",
      "Frenos IMR Racing con discos 180mm delantero y trasero.",
      "Llantas IMR Racing de 10 pulgadas.",
      "Incluye cubremanos, protector de chasis/escape y pata de cabra.",
      "Dimensiones: 1080mm entre ejes, 680mm altura asiento, 1495mm largo, 640mm ancho.",
      "Peso 62,5kg.",
      "No incluye neumaticos ni caballete.",
    ],
  },
  {
    slug: "corse-110r",
    name: "IMR Corse 110R",
    image: "https://impormotor.com/19449-home_default/pitbike-imr-corse-110r-modelo-2025.jpg",
    summary: "110cc automatica con arranque electrico y parte ciclo regulable.",
    audience: "Para pilotos que suben desde 90cc y buscan mas altura y control.",
    specs: [
      "Motor 4T 110cc refrigerado por aire y aceite.",
      "Potencia indicada: 6,5cv.",
      "Cambio automatico y arranque electrico.",
      "Chasis acero tubular tipo Copa; basculante aluminio tipo cantilever.",
      "Horquilla invertida 660mm, barras 37mm, anclaje axial.",
      "Amortiguador DNM 280mm con botella y regulacion.",
      "Freno delantero pinza axial 2 pistones con disco 190mm.",
      "Freno trasero con disco 180mm.",
      "Llantas IMR Racing de 12 pulgadas.",
      "Dimensiones: 117cm entre ejes, 78cm altura asiento, 99cm altura manillar, 76cm ancho.",
      "Peso 65kg.",
      "No incluye neumaticos ni caballete.",
    ],
  },
  {
    slug: "corse-140-rr",
    name: "IMR Corse 140 RR",
    image: "https://impormotor.com/19452-home_default/pitbike-imr-corse-140.jpg",
    summary: "Pitbike 140cc con embrague de 5 discos y horquilla de 660mm.",
    audience: "Para pilotos intermedios con ritmo en asfalto.",
    specs: [
      "Motor 4T 140cc refrigerado por aire y aceite.",
      "Potencia indicada: 14cv (10,30kw).",
      "Cambio manual de 4 marchas con embrague de 5 discos; aceite motor 750ml.",
      "Chasis acero tubular tipo Copa; basculante aluminio cantilever.",
      "Horquilla invertida regulable 660mm con barras 37mm.",
      "Amortiguador DNM 280mm con botella y regulacion.",
      "Freno delantero pinza axial 2 pistones con disco 190mm IMR Racing.",
      "Freno trasero con disco 180mm IMR Racing.",
      "Ruedas de aleacion 100/90-12 delante y 120/80-12 detras.",
      "Dimensiones: 117cm entre ejes, 78cm altura asiento, 99cm altura manillar, 76cm ancho.",
      "Peso 69kg.",
      "No incluye neumaticos ni caballete.",
    ],
  },
  {
    slug: "corse-155-rr",
    name: "IMR Corse 155 RR",
    image: "https://impormotor.com/19451-home_default/pitbike-imr-corse-155.jpg",
    summary: "Pitbike 155cc con horquilla regulable de 660mm y freno delantero 210mm.",
    audience: "Para pilotos que buscan mas par sin subir a 190cc.",
    specs: [
      "Motor 4T 155cc refrigerado por aire y aceite.",
      "Potencia indicada: 16cv (11,75kw).",
      "Cambio manual de 4 marchas con embrague de 6 discos.",
      "Chasis acero tubular tipo Copa; basculante aluminio cantilever.",
      "Horquilla invertida regulable 660mm con barras 37mm.",
      "Amortiguador DMN 275mm con botella y regulacion.",
      "Freno delantero con disco 210mm; freno trasero con disco 180mm.",
      "Llantas IMR Racing de 12 pulgadas.",
      "Incluye juego de cubremanetas.",
      "Dimensiones: 1170mm entre ejes, 780mm altura asiento, 990mm altura manillar, 760mm ancho.",
      "Peso 69kg.",
      "No incluye neumaticos ni caballete.",
    ],
  },
  {
    slug: "corse-190-rr",
    name: "IMR Corse 190 RR",
    image: "https://impormotor.com/19448-home_default/pitbike-imr-corse-rr-modelo-5k.jpg",
    summary: "Pitbike 190cc con horquilla regulable y frenos IMR Racing.",
    audience: "Para pilotos avanzados que quieren 190cc en asfalto.",
    specs: [
      "Motor 4T 190cc refrigerado por aire y aceite.",
      "Potencia indicada: 19cv (13,97kw).",
      "Cambio manual de 5 marchas con embrague de 6 discos.",
      "Chasis acero tubular tipo Copa; basculante aluminio cantilever.",
      "Horquilla invertida regulable 660mm con barras 37mm.",
      "Amortiguador DMN 275mm con botella y regulacion.",
      "Freno delantero con disco 220mm y trasero 180mm (MIR Racing).",
      "Llantas IMR Racing de 12 pulgadas.",
      "Incluye cubremanetas negros.",
      "Dimensiones: 1170mm entre ejes, 780mm altura asiento, 990mm altura manillar, 760mm ancho.",
      "Peso 65kg.",
      "No incluye neumaticos ni caballete.",
      "Evitar arrancar el motor con la pata de arranque por alta compresion.",
    ],
  },
  {
    slug: "race-pro-155",
    name: "IMR Race Pro 155",
    image: "https://impormotor.com/19444-home_default/pit-bike-imr-155-modelo-race-pro.jpg",
    summary: "Race Pro 155 alta con horquilla IMR V2 y freno delantero 240mm.",
    audience: "Para circuito y pilotos que buscan rigidez en asfalto.",
    specs: [
      "Motor 155Z 1 cilindro 4T refrigerado por aceite.",
      "Potencia indicada: 16cv (11,93kw).",
      "Cambio manual de 4 marchas con embrague de 6 discos.",
      "Chasis de acero con cuna de doble tubo; basculante de acero.",
      "Manillar aluminio 28mm; incluye cubremanetas.",
      "Horquilla invertida ajustable modelo IMR V2.",
      "Amortiguador DNM ajustable con 4 posiciones.",
      "Freno delantero con disco flotante 240mm y pinza doble piston.",
      "Freno trasero con disco 180mm y pinza de un piston.",
      "Llantas ultraligeras de aluminio 12 pulgadas.",
      "Estriberas CNC regulables.",
      "Capacidad deposito 4L.",
      "Altura asiento 820mm; distancia entre ejes 1220mm.",
      "Vehiculo no matriculable.",
      "No incluye neumaticos ni caballete.",
    ],
  },
  {
    slug: "race-pro-190",
    name: "IMR Race Pro 190",
    image: "https://impormotor.com/19445-home_default/pit-bike-imr-190-modelo-race-pro.jpg",
    summary: "Race Pro 190 con horquilla IMR V2 y llantas de 12 pulgadas.",
    audience: "Para pilotos que quieren potencia y estabilidad en asfalto.",
    specs: [
      "Motor 1 cilindro 4T 190cc refrigerado por aceite.",
      "Potencia indicada: 19cv (13,97kw).",
      "Cambio manual de 5 marchas con embrague de 6 discos.",
      "Chasis de acero con cuna de doble tubo; basculante de acero.",
      "Manillar aluminio 28mm; incluye cubremanetas.",
      "Horquilla invertida ajustable modelo IMR V2.",
      "Amortiguador DNM ajustable con 4 posiciones.",
      "Freno delantero con disco flotante 240mm y pinza doble piston.",
      "Freno trasero con disco 180mm y pinza de un piston.",
      "Llantas ultraligeras de aluminio 12 pulgadas.",
      "Estriberas CNC regulables.",
      "Capacidad deposito 4L.",
      "Altura asiento 820mm; distancia entre ejes 1220mm.",
      "Vehiculo no matriculable.",
      "No incluye neumaticos ni caballete.",
      "Evitar arrancar el motor con la pata de arranque por alta compresion.",
    ],
  },
  {
    slug: "gp20-160",
    name: "IMR GP20 160",
    image: "https://impormotor.com/19454-home_default/pitbike-imr-gp20-160.jpg",
    summary: "GP20 160 con chasis CrMo, frenos Formula y parte ciclo MIR Racing.",
    audience: "Para pilotos que entrenan y compiten en circuito.",
    specs: [
      "Motor 1 cilindro 4T 160cc.",
      "Potencia indicada: 16cv (11,93kw).",
      "Chasis tubular de cromo molibdeno.",
      "Basculante de aluminio con sistema de bieletas.",
      "Horquillas MIR Racing radiales regulables; tijas MIR CNC.",
      "Amortiguacion trasera DNM.",
      "Bomba de freno Formula.",
      "Pinza delantera Formula radial con disco flotante 220mm.",
      "Pinza trasera MIR Racing con disco 180mm.",
      "Palanca de cambio regulable MIR Racing y tensores de cadena GP.",
      "Llantas ultraligeras de 12 pulgadas color negro.",
      "Peso llanta delantera 2,2kg; trasera 2,4kg.",
      "Dimensiones: 750mm altura asiento, 950mm altura manillar, 1150mm entre ejes.",
      "Incluye neumaticos PMT y caballete trasero.",
      "Opcionales: horquillas Andreani, Mychron, telemetria, segundo juego de llantas.",
    ],
  },
  {
    slug: "gp20-190",
    name: "IMR GP20 190",
    image: "https://impormotor.com/19446-home_default/pitbike-imr-gp20-190.jpg",
    summary: "GP20 190 con chasis CrMo, frenos Formula y parte ciclo MIR Racing.",
    audience: "Para pilotos competitivos que buscan 190cc en asfalto.",
    specs: [
      "Motor 1 cilindro 4T 190cc.",
      "Potencia indicada: 20cv (14,91kw).",
      "Chasis tubular de cromo molibdeno.",
      "Basculante de aluminio con sistema de bieletas.",
      "Horquillas MIR Racing radiales regulables; tijas MIR CNC.",
      "Amortiguacion trasera DNM.",
      "Bomba de freno Formula.",
      "Pinza delantera Formula con disco flotante 220mm.",
      "Pinza trasera MIR Racing con disco 180mm.",
      "Tensores de cadena GP.",
      "Llantas ultraligeras de 12 pulgadas color negro.",
      "Peso llanta delantera 2,2kg; trasera 2,4kg.",
      "Dimensiones: 750mm altura asiento, 950mm altura manillar, 1150mm entre ejes.",
      "Incluye neumaticos PMT y caballete trasero.",
      "Opcionales: horquillas Andreani, Mychron, telemetria, segundo juego de llantas.",
      "Evitar arrancar el motor con la pata de arranque por alta compresion.",
    ],
  },
  {
    slug: "gp20-190-daytona",
    name: "IMR GP20 190 Daytona",
    image: "https://impormotor.com/19455-home_default/pitbike-imr-gp20-190-daytona.jpg",
    summary: "GP20 con motor Daytona y componentes de freno Formula.",
    audience: "Para pilotos que buscan el maximo rendimiento en circuito.",
    specs: [
      "Motor Daytona 1 cilindro 4T 190cc.",
      "Potencia indicada: 24cv (17,89kw).",
      "Chasis tubular de cromo molibdeno.",
      "Basculante de aluminio con sistema de bieletas.",
      "Horquillas MIR Racing radiales regulables; tijas MIR CNC.",
      "Amortiguacion trasera DNM.",
      "Bomba de freno Formula.",
      "Pinza delantera Formula con disco flotante 220mm.",
      "Pinza trasera MIR Racing con disco 180mm.",
      "Tensores de cadena GP.",
      "Llantas ultraligeras de 12 pulgadas color negro.",
      "Peso llanta delantera 2,2kg; trasera 2,4kg.",
      "Dimensiones: 750mm altura asiento, 950mm altura manillar, 1150mm entre ejes.",
      "Incluye neumaticos PMT y caballete trasero.",
      "Opcionales: horquillas Andreani, Mychron, telemetria, segundo juego de llantas.",
      "Evitar arrancar el motor con la pata de arranque por alta compresion.",
    ],
  },
  {
    slug: "gp20-lc-300",
    name: "IMR GP20 LC 300",
    image: "https://impormotor.com/19447-home_default/pitbike-imr-lc-300.jpg",
    summary: "LC 300 con motor MIR Racing 280cc y parte ciclo de alta gama.",
    audience: "Para pilotos expertos que buscan maximo rendimiento en circuito.",
    specs: [
      "Motor MIR Racing 280cc 4T 4v.",
      "Potencia indicada: 35cv (26,09kw).",
      "Chasis tubular cromo molibdeno con pivot antisquat regulable.",
      "Basculante de aluminio con sistema de bieletas.",
      "Horquillas MIR Racing radiales regulables en compresion y extension.",
      "Tijas MIR Racing CNC con offset regulable.",
      "Amortiguador trasero DNM con sistema progresivo.",
      "Bomba de freno Formula o JJuan.",
      "Pinza delantera Formula o JJuan con disco flotante 240mm.",
      "Pinza trasera MIR Racing con disco 180mm.",
      "Llantas IMR UltraLigeras de 12 pulgadas.",
      "Peso llanta delantera 2,2kg; trasera 2,4kg.",
      "Incluye neumaticos PMT y caballete trasero.",
      "Opcionales: amortiguador de direccion, horquillas Andreani, Mychron, telemetria, segundo juego de llantas, frenos JJuan.",
    ],
  },
];

export const sharkModels: MotoModel[] = [
  {
    slug: "gp12",
    name: "Shark GP12",
    image: "https://sharkminigp.com/wp-content/uploads/2024/04/MINIGP-SHARK-GP12-PRECIO.jpeg",
    summary: "MiniGP con motor ZS190 y componentes racing listos para competir.",
    audience: "Para pilotos que buscan competir en MiniGP.",
    specs: [
      "Motor ZS190 segun proveedor.",
      "Chasis CrMo (cromo molibdeno).",
      "Frenos J.Juan con pinza radial 4 pistones.",
      "Disco de freno flotante 230mm.",
      "Horquillas regulables con precarga.",
      "Estriberas CNC.",
    ],
  },
  {
    slug: "mt12-190",
    name: "Shark MT12 190",
    image: "/pitbike-motard-shark-mt12-190cc.jpg",
    summary: "Pitbike MT12 190cc con configuracion racing para asfalto.",
    audience: "Para pilotos de pitbike asfalto con enfoque racing.",
    specs: [
      "190cc segun proveedor.",
      "Chasis CrMo (cromo molibdeno).",
      "Frenos J.Juan y horquillas regulables con precarga.",
      "Estriberas CNC.",
    ],
  },
];

export const motoBrands = {
  malcor: {
    name: "Malcor",
    models: malcorModels,
  },
  imr: {
    name: "IMR",
    models: imrModels,
  },
  shark: {
    name: "Shark",
    models: sharkModels,
  },
};
