import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import Image from "next/image";
import "./globals.css";
import Link from "next/link";
import { inter } from "./fonts";
import { routes } from "./common/routes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Analytics />
      <body className={`${inter.className} antialiased flex flex-col min-h-screen	`}>
        <header className="px-6 md:px-10 py-4 flex items-center shadow-xl">
          <Link href={routes.home.path}>
            <Image
              className="rounded-full"
              src="/icon.jpg"
              width={48}
              height={48}
              alt="pitbike-image"
            ></Image>
          </Link>
          <nav className="grow flex justify-end ">
            <Link href={routes.circuits.path}>Circuitos</Link>
          </nav>
        </header>
        <main className="grow">{children}</main>
      </body>
    </html>
  );
}
