import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import "./globals.css";
import { inter } from "./fonts";
import { Header } from "./common/ui/components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Analytics />
      <body
        className={`${inter.className} antialiased flex flex-col min-h-screen	`}
      >
        <Header />
        <main className="grow">{children}</main>
      </body>
    </html>
  );
}
